# Generated by Django 6.0.7 on 2026-07-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base rate per night', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available / Ready'), ('OCCUPIED', 'Occupied'), ('DIRTY', 'Dirty / Needs Housekeeping'), ('MAINTENANCE', 'Out of Order / Maintenance')], default='AVAILABLE', max_length=20)),
                ('max_capacity', models.IntegerField(default=2, help_text='Maximum guests allowed')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtier')),
            ],
        ),
    ]
