# Generated by Django 6.0.7 on 2026-07-15 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('borrower_name', models.CharField(help_text='Guest name/Room or Staff Member', max_length=150)),
                ('contact_info', models.CharField(blank=True, max_length=100, null=True)),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LostAndFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_found', models.CharField(help_text='e.g. Room 204 or Lobby Bar', max_length=200)),
                ('found_date', models.DateField()),
                ('status', models.CharField(choices=[('FOUND', 'Found & Secured'), ('CLAIMED', 'Claimed by Owner'), ('DONATED', 'Donated (Unclaimed)'), ('DISPOSED', 'Disposed')], default='FOUND', max_length=15)),
                ('finder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('claimant_name', models.CharField(blank=True, help_text='Filled when claimed', max_length=100, null=True)),
                ('claimant_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unit', models.CharField(choices=[('PCS', 'Pieces'), ('KG', 'Kilograms'), ('LITERS', 'Liters'), ('PACKS', 'Packs'), ('BOTTLES', 'Bottles')], default='PCS', max_length=10)),
                ('min_stock_level', models.DecimalField(decimal_places=2, default=5.0, help_text='Triggers low stock alert', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock_overview.category')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Stock In / Restock'), ('REMOVE', 'Stock Out / Issued'), ('DAMAGE', 'Reported Damaged'), ('MISSING', 'Reported Missing'), ('DONATION', 'Donation Outbound')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stock_overview.inventoryitem')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
